example_1/app/models.py
from app import db, login
from flask import current_app
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
import jwt
from time import time


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return 'User: {}'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode(
            {'reset_password': self.id, 'exp': time() + expires_in},
            current_app.config['SECRET_KEY'], algorithm='HS256')

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(token, current_app.config['SECRET_KEY'],
                            algorithms=['HS256'])['reset_password']
        except:
            return
        return User.query.get(id)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

example_1/app/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from config import Config
import logging
from logging.handlers import SMTPHandler, RotatingFileHandler
import os

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
mail = Mail()
bootstrap = Bootstrap()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    mail.init_app(app)
    bootstrap.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp, url_prefix='/errors')

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    def start_ngrok():
        from pyngrok import ngrok

        url = ngrok.connect(5000)
        print('* Tunnel: ', url)

    if app.config.get('ENV') == 'development' and app.config['START_NGROK']:
        start_ngrok()

    if not app.debug:
        if app.config['MAIL_SERVER']:
            auth = None
            if app.config['MAIL_USERNAME'] or app.config['MAIL_PASSWORD']:
                auth = (app.config['MAIL_USERNAME'],
                        app.config['MAIL_PASSWORD']
                        )
            secure = None
            if app.config['MAIL_USE_TLS']:
                secure = ()
            mail_handler = SMTPHandler(
                mailhost=(app.config['MAIL_SERVER'], app.config['MAIL_PORT']),
                fromaddr='no-reply@' + app.config['MAIL_SERVER'],
                toaddrs=app.config['ADMINS'], subject='Stripe Flask Failure',
                credentials=auth, secure=secure)
            mail_handler.setLevel(logging.ERROR)
            app.logger.addHandler(mail_handler)
        if app.config['LOG_TO_STDOUT']:
            stream_handler = logging.StreamHandler()
            stream_handler.setLevel(logging.INFO)
            app.logger.addHandler(stream_handler)
        else:
            if not os.path.exists('logs'):
                os.mkdir('logs')
            file_handler = RotatingFileHandler('logs/stripe_flask.log',
                                               maxBytes=10240,
                                               backupCount=10
                                               )
            file_handler.setFormatter(logging.Formatter(
                '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
            ))
            file_handler.setLevel(logging.INFO)
            app.logger.addHandler(file_handler)

        app.logger.setLevel(logging.INFO)
        app.logger.info('Stripe Flask Integration')
    return app

from app import models

example_1/app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

example_1/app/main/routes.py
from app.main import bp
from flask import render_template, jsonify, current_app, request
from flask_login import login_required
import stripe


@bp.route('/')
@bp.route('/home')
@login_required
def home():
    return render_template('home.html',
                           title='Home'
                           )


@bp.route('/config')
def get_publishable_key():
    stripe_config = {
        'publicKey': current_app.config['STRIPE_PUBLISHABLE_KEY']
    }
    return jsonify(stripe_config)


@bp.route('/create-checkout-session')
def create_checkout_session():
    domain_url = 'https://stripe-flask-integration.herokuapp.com/'
    stripe.api_key = current_app.config['STRIPE_SECRET_KEY']
    try:
        checkout_session = stripe.checkout.Session.create(
            # ?session_id={CHECKOUT_SESSION_ID} means the redirect will have
            # the session ID set as a query param
            # success_url=domain_url + 'success?session_id={CHECKOUT_SESSION_ID}'
            success_url=domain_url + 'success',
            cancel_url=domain_url + 'cancelled',
            payment_method_types=['card'],
            billing_address_collection='required',
            mode='payment',
            line_items=[
                {
                    'quantity': 1,
                    'price': 'price_1IYgbtFWpU2KHaPLODAVgoKU',
                }
            ]
        )
        return jsonify({'sessionId': checkout_session['id']})
    except Exception as e:
        return jsonify(error=str(e)), 403


@bp.route('/success')
def success():
    return render_template('success.html', title='Success')


@bp.route('/cancelled')
def cancel():
    return render_template('cancel.html', title='Cancel')


@bp.route("/webhook", methods=["POST"])
def stripe_webhook():
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get("Stripe-Signature")

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, current_app.config["STRIPE_ENDPOINT_SECRET"]
        )

    except ValueError as e:
        # Invalid payload
        return "Invalid payload", 400
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return "Invalid signature", 400

    # Handle the checkout.session.completed event
    if event["type"] == "checkout.session.completed":
        print("Payment was successful.")
        # TODO: you can run some custom code here

    return "Success", 200

example_1/app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Title Section -->
{% block title %}
    {% if title %}
        Stripe | {{ title }}
    {% else %}
        Flask Stripe
    {% endif %}
{% endblock %}

<!-- Head Section -->
{% block head %}
    {{ super() }}
    <link rel="icon" type="image/png" href="{{url_for('static', filename = 'images/stripe.svg')}}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
{% endblock %}

<!-- Link Styles -->
{% block styles %}
    {{ super() }}
    <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename = 'css/styles.css') }}">
{% endblock %}

<!-- Navbar Section -->
{% block navbar %}
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Stripe Flask</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">            
            <ul class="nav navbar-nav navbar-right">  
                {% if current_user.is_anonymous %}
                    <li><a href=" {{ url_for('auth.login') }} ">Login</a></li>
                {% else %}                                      
                    <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}                
            </ul>                       
        </div>
    </div>
</nav>
{% endblock %}

<!-- Blog Content Goes Here -->
{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert"> {{ message }} </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block app_content %}
        
        {% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="https://js.stripe.com/v3/"></script>
    <script src="{{ url_for('static', filename = 'js/app.js') }}"></script>
{% endblock %}

example_1/app/templates/cancel.html
{% extends "base.html" %}

{% block content %}
  <section class="section">
    <div class="container">
      <p>Your payment was cancelled.</p>
      <p><a href="{{ url_for('main.home') }}">Back to home page</a></p>
    </div>
  </section>
{% endblock %}

example_1/app/templates/home.html
{% extends 'base.html' %}

{% block app_content %}
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <!-- title -->
        <h1>Stripe and Flask Integration Demo</h1>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <p>Hi {{current_user.username}}, purchase an item below:</p>
    </div>
</div>
<!-- Add Purchase Button Card -->
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 col-xl-12 text-center">
        <div class="card" style="width: 18rem;">
            <img class="img-fluid" style="max-width: 50%; height: auto;"
                src="{{url_for('static', filename='images/automate_the_boring_stuff.jpg')}}" class="card-img-top"
                alt="Automate The Boring Stuff">
            <div class="card-body">
                <h4 class="card-title"><strong>Automate the Boring Stuff</strong></h4>
                <p class="card-text">Learn how to use Python to automate the boring stuff</p>
                <!-- Payment button -->
                <button class="button is-primary btn btn-primary" id="checkout-button">Purchase</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

example_1/app/templates/success.html
{% extends "base.html" %}

{% block content %}
  <section class="section">
    <div class="container">
      <p>Your payment succeeded.</p>
      <p><a href="{{ url_for('main.home') }}">Back to home page</a></p>
    </div>
  </section>
{% endblock %}